### ISSUE TITLE
CloudWatch is having issues

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#1]
Appears another icon is mixed in

<img width="265" alt="Screen Shot 2019-06-11 at 3 53 58 PM" src="https://user-images.githubusercontent.com/7776/59302111-2f9c4e80-8c61-11e9-8b93-f0c2e45811c4.png">

**Comment by karanbalaji** [comment]
## Fixed
![Screen Shot 2019-06-12 at 2 10 45 PM](https://user-images.githubusercontent.com/16112411/59375317-e4934180-8d1b-11e9-99e3-21f20aac0a53.png)
