### ISSUE TITLE
Management & Governance Weird Orange Artifact

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#2]
<img width="228" alt="Screen Shot 2019-06-11 at 3 55 05 PM" src="https://user-images.githubusercontent.com/7776/59302158-5195d100-8c61-11e9-9c9b-4c53d3055690.png">

Part of this icon is a little orange line. I don't believe that is supposed to be there.
Here you can see under Robotics similar issue. Its not part of the group but we need to scrub these things:

<img width="366" alt="Screen Shot 2019-06-11 at 3 55 47 PM" src="https://user-images.githubusercontent.com/7776/59302226-768a4400-8c61-11e9-8fd1-974d50dc421a.png">

Here's another one:

<img width="120" alt="Screen Shot 2019-06-11 at 4 09 58 PM" src="https://user-images.githubusercontent.com/7776/59303073-712df900-8c63-11e9-9956-8754a0052f20.png">

**Comment by karanbalaji** [comment]
## Fixed Orange Dash
![Screen Shot 2019-06-12 at 2 08 53 PM](https://user-images.githubusercontent.com/16112411/59375226-aac23b00-8d1b-11e9-8752-106ac015e47e.png)
