### ISSUE TITLE
Can't find AWS Inspector via asset search:

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#3]
So I needed AWS Inspector but couldn't find it.

<img width="349" alt="Screen Shot 2019-06-11 at 3 56 39 PM" src="https://user-images.githubusercontent.com/7776/59302266-928de580-8c61-11e9-8c6b-d0e23516d97e.png">

**Comment by karanbalaji** [comment]
## Fixed AWS Inspector Rename which was named as guard duty
![Screen Shot 2019-06-12 at 1 59 26 PM](https://user-images.githubusercontent.com/16112411/59374645-4eaae700-8d1a-11e9-9ea5-539e054e5121.png)
