### ISSUE TITLE
Rename Assets to be more easily readable in the assets window.

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#4]
So here I need to search for GaurdDuty so I type duty.
I can't really tell which is which. This is because Adobe XD cuts of the name:

<img width="306" alt="Screen Shot 2019-06-11 at 3 57 29 PM" src="https://user-images.githubusercontent.com/7776/59302319-b4876800-8c61-11e9-927d-ad1ffcbfe707.png">

If I perfectly stretch it I can get the full name
<img width="326" alt="Screen Shot 2019-06-11 at 3 58 50 PM" src="https://user-images.githubusercontent.com/7776/59302375-db459e80-8c61-11e9-822c-923a9c56d69e.png">

Though XD is most likely going to do this so I'll never see the name of the few:

<img width="363" alt="Screen Shot 2019-06-11 at 3 58 58 PM" src="https://user-images.githubusercontent.com/7776/59302400-ea2c5100-8c61-11e9-9b93-ff8d2d31b07a.png">

I think maybe we are better off just renaming these components.
The reason I thought "Product - Security, Identify & Compliance - GuardDuty" would have made sense was so that it was alphabetically but realizing you normally know what you want and you don't browse via assets.

I think we can rename them to be just what they are so:

"Product - Security, Identify & Compliance - GuardDuty"

becomes

"GaurdDuty"

Clearly there is a service that is mislabeled. Maybe this is why I can't find Inspector.

**Comment by karanbalaji** [comment]
## Renamed & Fixed AWS Inspector
![Screen Shot 2019-06-12 at 1 58 31 PM](https://user-images.githubusercontent.com/16112411/59374598-34710900-8d1a-11e9-8d55-b1fc7e541ddf.png)
