### ISSUE TITLE
When stretch icons should scale correctly

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#5]
Started streching and weirds thing were happening.

<img width="263" alt="Screen Shot 2019-06-11 at 4 02 30 PM" src="https://user-images.githubusercontent.com/7776/59302643-6a52b680-8c62-11e9-95bb-fd286960aed1.png">

I think this is because responsive resize is on

<img width="278" alt="Screen Shot 2019-06-11 at 4 03 41 PM" src="https://user-images.githubusercontent.com/7776/59302695-85bdc180-8c62-11e9-9ea9-3535e91d302d.png">

In the UI kit I think it needs to be toggle for all icons

**Comment by karanbalaji** [comment]
## Set default off on responsive resize for all icons & resources 
![Screen Shot 2019-06-12 at 1 42 30 PM](https://user-images.githubusercontent.com/16112411/59373581-f4a92200-8d17-11e9-9648-7f09ce318cde.png)
