### ISSUE TITLE
arrows line body needs to be an Adobe XD line

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#6]
I can tell when I look at the arrow that the line body is not an actual line is a rectangular path.
This causes issues when you want to drag out these arrows.

<img width="380" alt="Screen Shot 2019-06-11 at 4 06 14 PM" src="https://user-images.githubusercontent.com/7776/59302848-e6e59500-8c62-11e9-9c47-0f41be76e66b.png">

Can we get the line body be a line and keep the arrowhead as a path object.
Because they are not separate

<img width="539" alt="Screen Shot 2019-06-11 at 4 07 54 PM" src="https://user-images.githubusercontent.com/7776/59302946-23b18c00-8c63-11e9-9239-ec3ababaeb84.png">
 objects in a group this is what happens when you stretch:

**Comment by karanbalaji** [comment]
Rebuilt and fixed all the stretching of arrows
![Screen Shot 2019-06-12 at 1 39 10 PM](https://user-images.githubusercontent.com/16112411/59373353-7c426100-8d17-11e9-8b4e-12b75148efab.png)
