### ISSUE TITLE
Loose incomplete graphic in the Group page

### ISSUE THREAD

**Issue by omenking** [ExamProCo/aws-xd-ui-kit#7]
I think this is a mistake just needs to get deleted.

<img width="278" alt="Screen Shot 2019-06-11 at 4 08 50 PM" src="https://user-images.githubusercontent.com/7776/59303013-4cd21c80-8c63-11e9-90c0-590d023702ab.png">

**Comment by karanbalaji** [comment]
## Can't Find This or Probably already deleted ?
![Screen Shot 2019-06-12 at 2 15 56 PM](https://user-images.githubusercontent.com/16112411/59375657-a34f6180-8d1c-11e9-82ca-0bc51a8441f6.png)
